### ISSUE TITLE
github sponsor

### ISSUE THREAD

**Issue by alexn-s** [Gerrnperl/outline-map#1]
just downloaded your extension and i love it. 
it is superior to the native vscode outline pane.

i want to support/ sponsor your project on github.
perhaps you can add that option.

i appreciate your work 💖

**Comment by Gerrnperl** [comment]
Thank you for your support!💖

I have added two links (buymeacoffee and paypal) (github sponsor is not supported in my country yet)

**Comment by alexn-s** [comment]
great. just sent you something over paypal.
i hope you have a nice week
