### ISSUE TITLE
qml support

### ISSUE THREAD

**Issue by gushuguo** [Gerrnperl/outline-map#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gushuguo** [comment]
the qml language might be not supported now, when I switch to qml file, the outline view won't updated

**Comment by Gerrnperl** [comment]
This extension relies on vscode OR other extensions to provide symbol information

If the build-in outline view can't display qml outline, this extension can't work as well.

![Screenshot_20220729_102950](https://user-images.githubusercontent.com/64595686/181670457-744ad574-6cca-4f22-8106-c01adfc53667.png)
