### ISSUE TITLE
能不能点中了再展开，鼠标一滑就展开了，收不住

### ISSUE THREAD

**Issue by wuyonggang100** [Gerrnperl/outline-map#11]
能不能点中了再展开，鼠标一滑就展开了，收不住

**Comment by Endless-reincarnation** [comment]
+1

**Comment by zhoushaokun** [comment]
+1
而且当滑的比较底部，鼠标没搞好移出去了， 就会出现如图情况，按道理都被收起来了，但是还会有滚动条，需要我们再滚到上面才能展开，使用起来比较难受，
![image](https://user-images.githubusercontent.com/32841670/181694764-8fb2908d-dc24-4554-a395-4b639a1d03e6.png)

**Comment by Gerrnperl** [comment]
完成。

[v0.7.1] 现在可以选择点击图标展开（点击名称跳转）

保留了鼠标悬停展开的选项

Completed.

[v0.7.1] Now you can click the icon to expand (click the name to jump to code)

The option to expand on mouseover is preserved

![click-expand](https://user-images.githubusercontent.com/64595686/181703147-2cb94654-028b-4e4e-bcba-06d62c8589e0.gif)
