### ISSUE TITLE
show level between left arrow and right arrow

### ISSUE THREAD

**Issue by chenbimo** [Gerrnperl/outline-map#13]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/33003566/181680863-f04f7609-7fac-4e11-998d-0a6a8a951128.png)

**Describe the solution you'd like**

like the picture,when i click left arrow or right arrow,that can show the level between left arrow and right arrow.

**Describe alternatives you've considered**

**Additional context**

**Comment by Gerrnperl** [comment]
I can't seem to put anything other than buttons here
But I think it is necessary to show the current depth
So I added a Toast
![Toast](https://user-images.githubusercontent.com/64595686/181867170-281aa273-bfab-40ca-8ea1-09cb573bd67d.gif)

**Comment by chenbimo** [comment]
nice.
