### ISSUE TITLE
custom Font, such as monospaced font

### ISSUE THREAD

**Issue by pizberg** [Gerrnperl/outline-map#14]
Great works, very cool project!

**Comment by Gerrnperl** [comment]
Completed.
v0.7.3
![Screenshot_20220802_072226](https://user-images.githubusercontent.com/64595686/182261955-e7ee8691-732d-4e5a-8572-0005edb8efd3.png)

**Comment by pizberg** [comment]
set custom font as 'Consolas, "Courier New", monospace', but there is no effect.

Outline-map:
0.7.3

VS Code:
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by Gerrnperl** [comment]
This font family works well in my vscode & vscode.dev 🤷
1. Have you tried restarting vscode?
2. Can other fonts take effect?
3. Can this font family take effect in the editor settings (font>font family)?

---

If there is no problem with the above, could you please provide the font family set for the outline in the developer tools (Help > Toggle Developer Tools)

![Screenshot_20220809_223920](https://user-images.githubusercontent.com/64595686/183679457-9ae1ed8d-71c0-44fa-a490-cabfd6333e2b.png)

**Comment by pizberg** [comment]
![image](https://user-images.githubusercontent.com/10650959/183861234-e4ba6fb9-b63f-4a99-aa21-8d7f2108ae41.png)

**Comment by pizberg** [comment]
It works as 'Consolas, "Courier New", monospace' after restart the VSCode.
Thks.
