### ISSUE TITLE
「Feature」大纲不随光标滚动而自动收起

### ISSUE THREAD

**Issue by gyk0818** [Gerrnperl/outline-map#15]
现有的大纲会在用户光标滚动时自动收起，能否新增配置取消自动收起的能力

**Comment by Gerrnperl** [comment]
你可以在展开后点击视图右上角的`📌`一次来禁用自动收起（两次禁用滚动）

如果这不符合需求, 请详细描述

**Comment by gyk0818** [comment]
完美解决问题，感谢~
