### ISSUE TITLE
Feature - Expand Outline Method - "always open"

### ISSUE THREAD

**Issue by Hecatoncheir** [Gerrnperl/outline-map#16]
Need some way to get always opened tree without click on something, like default outline:
![Screenshot 2022-08-02 at 14 04 11](https://user-images.githubusercontent.com/910917/182360254-ed38a7cd-9222-405b-a42e-a3bc092a6932.png) ![Screenshot 2022-08-02 at 14 00 10](https://user-images.githubusercontent.com/910917/182360266-42de97c3-88ca-4d39-8ad9-ae4304824429.png)

Maybe add another one method "`always open`" to settings:
![Screenshot 2022-08-02 at 13 53 37](https://user-images.githubusercontent.com/910917/182360520-783f8efa-f933-42b2-a3be-97d78a0a221e.png)

**Comment by Gerrnperl** [comment]
I added another option `cursor-always-open`

For this option: 

- The outline will not expand/collapse automatically when you scroll the editor

- The outline will still scroll, following the cursor position

Hope it fits your needs

**Comment by Hecatoncheir** [comment]
Yes, that's so good. Thx!
