### ISSUE TITLE
切到别的文件再切回来会导致大纲全部关闭，需要重新打开

### ISSUE THREAD

**Issue by gyk0818** [Gerrnperl/outline-map#18]

**Comment by Gerrnperl** [comment]
原生的大纲好像也会在切文件时折叠节点

要保持大纲状态，感觉开销有点大。
1.不能释放大纲的信息，增加内存占用
2.如果在切出文件后该文件在外部更改了，暂存的大纲信息就可能无效了

可能会在以后实现吧，目前无计划
