### ISSUE TITLE
希望根据光标位置在大纲中高亮对应的函数体或变量.

### ISSUE THREAD

**Issue by KumaCool** [Gerrnperl/outline-map#19]
**Is your feature request related to a problem? Please describe.**
目前大纲会根据视窗进行展开.
但一眼扫过去很难定位到你想要的函数体或变量

**Describe the solution you'd like**
需要类似miniMap光标所在行高亮的功能
比如光标所在的函数体,在大纲中对应的函数进行高亮显示.

**Describe alternatives you've considered**

**Additional context**

**Comment by Gerrnperl** [comment]
这个已经有的特性是不符合预期吗
![Screenshot_20221013_131210](https://user-images.githubusercontent.com/64595686/195507332-a90f3db2-0779-4fc9-a6c6-ded1a873468b.png)
