### ISSUE TITLE
[Feature Request] Display functions return type and params type

### ISSUE THREAD

**Issue by GustafXTT** [Gerrnperl/outline-map#25]
在Java中outline_map只会显示函数返回类型，不会显示函数参数类型，
在C++中ouline_map只会显示一个函数名。

在Vscode的原生outline中，函数的返回类型和参数类型会与函数名分开，单独开一个小块显示（以C++为例），可能outline_map没有把那个小块也做进来？

![Snipaste_2022-09-12_02-31-45](https://user-images.githubusercontent.com/62175622/189538769-f4779f02-f269-4015-a780-73578975b46f.jpg)
![Snipaste_2022-09-12_02-31-30](https://user-images.githubusercontent.com/62175622/189538783-a1e36674-50bf-4090-b100-c83e078f8dda.jpg)

**Comment by Gerrnperl** [comment]
[v0.8.1]
加入此功能
![details-2](https://user-images.githubusercontent.com/64595686/195506419-66f1783e-5081-455a-9c7d-cfb4e26de4ff.png)
