### ISSUE TITLE
Make outline expand automaticly when editor is opened

### ISSUE THREAD

**Issue by pronode** [Gerrnperl/outline-map#27]
Hello!

Is it possible to make Outline Map to automaticaly show me properties and methods without clicking expand button every time I change the file?

**Comment by Gerrnperl** [comment]
[v0.8.1]
before
![before](https://user-images.githubusercontent.com/64595686/195506006-efb9408c-177a-463e-af9d-f1f824a7e389.gif)
after
![after](https://user-images.githubusercontent.com/64595686/195506009-ab60034b-7dde-4a5c-94fd-788a64f02264.gif)
Hope this meets your expectations
