### ISSUE TITLE
Always highlight the nearest outline item

### ISSUE THREAD

**Issue by jiewangjs** [Gerrnperl/outline-map#34]
Thanks to the author for such a nice extension.
As I have suggested in the title, right now, when viewport has no outline item, the highlight on the outline map lost, it is very easy to lose track. 
I ponder this feature won't be hard, hope this can be added.

**Comment by Gerrnperl** [comment]
Thanks for your suggestion :). I'm sorry I almost forgotten this point, and now the extension will try to focus on the closest item to the selection area when no symbol is selected.
