### ISSUE TITLE
搜索窗口会挡住大纲的部分

### ISSUE THREAD

**Issue by Ekkone** [Gerrnperl/outline-map#39]
**描述Bug**
搜索窗口会挡住大纲的最后一行部分

**复现**
一直复现
**期望表现**
搜索窗口不占用显示的空间
**截屏/录屏**
![image](https://github.com/Gerrnperl/outline-map/assets/38444906/f094e524-2c18-4df7-8235-455639bb42e7)
**信息**
 - VSCode Version* :
 - Outline-map Version* :
 - 相关文件 : [eg: github.com/......]
 -相关插件: [eg: vue.volar]
 - 扩展设置: 

**附加信息**

**Comment by Gerrnperl** [comment]
现在我改变了搜索区域的位置（v1.1.0），应该不会出现遮挡问题了。
