### ISSUE TITLE
[FR] Region Support

### ISSUE THREAD

**Issue by Servinjesus1** [Gerrnperl/outline-map#43]
Requests to get regions (manual code folding breakpoints) to show up in the VSCode outline [are being ignored](https://github.com/microsoft/vscode/issues/51364). It would be incredible if this plugin implemented this instead.

For the large python scripts I work on, for example, I have lots of symbols being defined and sections I am trying to refactor, but aren't yet refactored into their own functions. While I work on that, being able to add `#region Code Does This` and `#endregion` around certain blocks can help me separate steps.

In Outline Map, it would be awesome if those regions showed up in the outline underneath the function they are a part of, and the symbols within that region showed up as symbols underneath the region. Additionally, regions within regions would be underneath their parent regions.

I'm not sure how to handle regions people put that start in one context and end in another (like start before a function and end within that function), maybe by default the region becomes the parent since it began above the function it ends in? That will have to be something we think about, but for a first attempt, just showing regions in the outline map would be incredible.

**Comment by Gerrnperl** [comment]
Thanks for your advice.

I had always thought that this feature will require a lot of work and should be completed by other extensions.

But no matter what, I have now implemented this feature.

![Screenshot_20231013_201509](https://github.com/Gerrnperl/outline-map/assets/64595686/107b484f-cf7f-476b-81fd-f413e4b24539)


In theory, this feature now works in all languages.

I will release this version after some modifications.
