### ISSUE TITLE
Follow setting not working when set to Manual

### ISSUE THREAD

**Issue by YousufSSyed** [Gerrnperl/outline-map#53]
**Describe the bug**
When the follow setting is set to manual, it still automatically scrolls and expands.

**To Reproduce**
1. Set following setting to manual
2. Go to another section in the file.

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Version: 1.3.2

**Comment by Gerrnperl** [comment]
I should have fixed this bug in the new version (v1.4.0). Please set both `outline-map.follow` and `outline-map.expand` to `manual` to disable automatic scrolling and expansion. 

If there are still problems, please reopen this issue.
