### ISSUE TITLE
Sorting Items A to Z

### ISSUE THREAD

**Issue by ozum** [Gerrnperl/outline-map#54]
Hi,

Thanks for this great extension. It would be nice to be able to sort functions or methods alphabetically A to Z.

Kind Regards,

**Comment by Gerrnperl** [comment]
![image](https://github.com/Gerrnperl/outline-map/assets/64595686/2d30e935-a0fc-4876-8d20-c6a1214a3ed6)

**Comment by iBook140** [comment]
Hello,

on first open sorting doesn’t work A to Z.

Can you please tell me what "Pin" does?

Kind regards
René
