### ISSUE TITLE
在Python类中 region表现不符合预期

### ISSUE THREAD

**Issue by Yuelioi** [Gerrnperl/outline-map#56]
**Bug 描述**

当在python class中使用region时, 无法覆盖到最后一个函数, 如果region包含最后一个函数,则该region会失效

![20240102-06064827.png](https://cdn.yuelili.com/github/20240102-06064827.png)

- windows
- vscode 1.85.1

**Comment by joshua-dean** [comment]
+1
I have encountered the same issue - any region containing the last function in a class definition doesn't work correctly, getting placed at the end of the outline. This occurs regardless of the "Start Region" and "End Region" settings (I tried both `# region` and `#region`). 

Having any statement after the "End Region" does show the outline correctly.
![image](https://github.com/user-attachments/assets/95d6cbd7-34dd-4a5c-9a29-badc5c4b6b20)

Setup:
- Ubuntu 22.04.2 LTS
- vscode 1.90.1 x64
- Outline Map v1.4.0

**Comment by joshua-dean** [comment]
I think this is because the `DocumentSymbol` for the class defines the end range as the last source line, which doesn't include the last `# endregion`.

I will try to see if there is an easy way to handle this - I am still familiarizing myself with the codebase.

**Comment by joshua-dean** [comment]
I have a fix here: https://github.com/joshua-dean/outline-map/commit/855f89599fccebc72b7350d53b1b5d4b7f0137a7

When calling `reconstructTree`, if the sibling is a "region", it only checks the start, not the end.

Result:
![image](https://github.com/user-attachments/assets/adae3cb5-af89-4733-b8b5-e9dbbedee596)

I am not sure if this is the best property to check. It doesn't seem to create any other issues.

I think this is only an issue with languages like python that use indentation for scope - languages like JavaScript have closing brackets that would ensure the region is contained. We might want to query the language for checks like this. 

Are there any linting/formatting/testing I should complete, or do you think I'm good to open a PR?

**Comment by joshua-dean** [comment]
@Yuelioi The 1.4.1 release fixed this for me. Is this issue also solved for you?

**Comment by Yuelioi** [comment]
> @Yuelioi The 1.4.1 release fixed this for me. Is this issue also solved for you?

Yes, it works well now
