### ISSUE TITLE
Cannot execute command: next primary side bar view

### ISSUE THREAD

**Issue by HenryC-3** [Gerrnperl/outline-map#6]
## Describe the bug
Cannot execute  views: next primary side bar view when focus on outline map view.

## To Reproduce
1. put  outline map view in the primary side bar
2. use command palette execute the command "views: next primary side bar view"

Cycle through primary side bar views that contains outline map view.

![sidebar-navigation-failed](https://user-images.githubusercontent.com/41246463/181214899-25dc94b5-59c9-4001-aecb-e068643c637c.gif)
> in the gif above, I use shortcut `cmd+alt+left & right` to nav back/forward views

## Expected behavior

Cycle through primary side bar views that not contains outline map view.

![sidebar-navigation-success](https://user-images.githubusercontent.com/41246463/181214935-fd0c51e7-a5c3-4db6-a337-f9eadc86369d.gif)
> in the gif above, I use shortcut `cmd+alt+left & right` to nav back/forward views

**Comment by Gerrnperl** [comment]
Strangely it works fine on my vscode
![Peek 2022-07-27 18-16](https://user-images.githubusercontent.com/64595686/181227505-e0326a65-bb42-496a-9507-1937b3a22fd5.gif)
But I also tested its performance on vscode.dev, it can be switched, but there will be lags.
![Peek 2022-07-27 18-40](https://user-images.githubusercontent.com/64595686/181228287-2c6aec4d-0683-4b3a-92c7-0344935992cc.gif)

**Comment by HenryC-3** [comment]
Thanks for the quick response.

It turns out my custom keybinding settings caused this problem.

The command works fine after disabling  `"when": "sidebarFocus"`

```JSON
{
  "key": "alt+cmd+left",
  "command": "workbench.action.previousSideBarView",
  "when": "sidebarFocus"
}
```
> keybinding.json

This issue will be closed since it is not related to outline map core functionality.
