### ISSUE TITLE
Outline map scrolls to the top always when scrolling some files

### ISSUE THREAD

**Issue by Tyriar** [Gerrnperl/outline-map#7]
**To Reproduce**
1. Open https://github.com/xtermjs/xterm.js/blob/master/src/browser/Terminal.ts
2. Click somewhere, the outline map will get revealed correctly
3. Scroll up, 🐛 the outline map scrolls to the top

**Expected behavior**
If should keep revealing when scrolling

**Screenshots**

Had to cut the gif a bit to get it below 10mb, hopefully it's clear:

![Recording 2022-07-27 at 04 57 29](https://user-images.githubusercontent.com/2193314/181241476-b296a053-3713-4fad-a1ec-e0ad7bb74b1b.gif)

Version: 1.70.0-insider (user setup)
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:16:55.337Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

ext: v0.5.2

**Comment by Gerrnperl** [comment]
Completed.

In the new version v0.5.3, the outline scrolls fine (on my vscode). 

If there are still problems, please open another issue
