### ISSUE TITLE
do not follow cursor and viewport

### ISSUE THREAD

**Issue by chenbimo** [Gerrnperl/outline-map#8]
**Is your feature request related to a problem? Please describe.**

i hope i can see all the outline，becase it can make me more global outlook

我希望我可以查看所有的大纲，因为它可以让我保持对页面的全局把握

**Describe the solution you'd like**

just setup a switch,that i can toggle it  follow cursor and viewport or not follow cursur and viewport.

只需要设计一个开关，我可以切换它来控制是否跟随光标和视窗或者不跟随光标和视窗

Alternatively，provide the third option is "none"，that i can choose it to not follow cursor.
或者，提供第三个选项“none”，我可以选择这个选项，避免光标跟随

**Describe alternatives you've considered**

**Additional context**

**Comment by Gerrnperl** [comment]
Completed.
[v0.6.1] Now you can 📌 the outline
